import type { Product, Swap } from "./types";

// Curated seed catalogue. Prices are typical shelf prices (approximate) as of mid-2026.
// Certifications should be re-verified periodically at leapingbunny.org and crueltyfree.peta.org.

const CA = ["Shoppers Drug Mart", "Walmart Canada", "Well.ca", "Amazon.ca", "London Drugs"];
const US = ["Target", "Walmart", "CVS", "Walgreens", "Amazon.com"];

type P = Omit<Product, "id" | "upvotes" | "downvotes">;

const p = (x: P): Product => ({ ...x, id: x.slug, upvotes: 0, downvotes: 0 });

export const seedProducts: Product[] = [
  // ---------- MAKEUP ----------
  p({ slug: "elf-lash-n-roll-mascara", name: "Lash 'N Roll Mascara", brand: "e.l.f.", category: "Makeup",
    description: "Curling, lengthening mascara. 100% vegan and cruelty-free at a drugstore price.",
    price_cad: 8, price_usd: 6, certification: "PETA", vegan: true, emoji: "👁️",
    stores_ca: ["Shoppers Drug Mart", "Walmart Canada", "Amazon.ca"], stores_us: ["Target", "Walmart", "CVS"],
    available_ca: true, available_us: true, tags: ["mascara", "eyes", "budget"] }),
  p({ slug: "essence-lash-princess", name: "Lash Princess False Lash Effect Mascara", brand: "Essence", category: "Makeup",
    description: "Cult-favourite volumizing mascara, consistently rated on par with prestige brands.",
    price_cad: 7, price_usd: 5, certification: "PETA", vegan: true, emoji: "👁️",
    stores_ca: ["Shoppers Drug Mart", "Amazon.ca", "Walmart Canada"], stores_us: ["Target", "Walmart", "Ulta"],
    available_ca: true, available_us: true, tags: ["mascara", "eyes", "budget", "bestseller"] }),
  p({ slug: "covergirl-lashblast-volume", name: "LashBlast Volume Mascara", brand: "CoverGirl", category: "Makeup",
    description: "Classic volumizing mascara from a fully Leaping Bunny certified drugstore brand.",
    price_cad: 12, price_usd: 9, certification: "Leaping Bunny", vegan: false, emoji: "👁️",
    stores_ca: CA, stores_us: US, available_ca: true, available_us: true, tags: ["mascara", "eyes"] }),
  p({ slug: "elf-flawless-satin-foundation", name: "Flawless Satin Foundation", brand: "e.l.f.", category: "Makeup",
    description: "Medium-coverage satin-finish foundation in 40 shades. Vegan.",
    price_cad: 10, price_usd: 8, certification: "PETA", vegan: true, emoji: "🧴",
    stores_ca: ["Shoppers Drug Mart", "Walmart Canada", "Amazon.ca"], stores_us: ["Target", "Walmart", "CVS"],
    available_ca: true, available_us: true, tags: ["foundation", "face", "budget"] }),
  p({ slug: "covergirl-clean-fresh-foundation", name: "Clean Fresh Skin Milk Foundation", brand: "CoverGirl", category: "Makeup",
    description: "Lightweight hydrating foundation, Leaping Bunny certified.",
    price_cad: 15, price_usd: 11, certification: "Leaping Bunny", vegan: true, emoji: "🧴",
    stores_ca: CA, stores_us: US, available_ca: true, available_us: true, tags: ["foundation", "face"] }),
  p({ slug: "nyx-butter-gloss", name: "Butter Gloss", brand: "NYX Professional Makeup", category: "Makeup",
    description: "Buttery-soft lip gloss in 30+ shades. PETA certified brand.",
    price_cad: 7, price_usd: 5, certification: "PETA", vegan: false, emoji: "💄",
    stores_ca: ["Shoppers Drug Mart", "Amazon.ca", "London Drugs"], stores_us: ["Target", "Ulta", "CVS"],
    available_ca: true, available_us: true, tags: ["lips", "gloss", "budget"] }),
  p({ slug: "elf-o-face-satin-lipstick", name: "O FACE Satin Lipstick", brand: "e.l.f.", category: "Makeup",
    description: "Full-coverage satin lipstick, vegan and cruelty-free.",
    price_cad: 11, price_usd: 9, certification: "PETA", vegan: true, emoji: "💄",
    stores_ca: ["Shoppers Drug Mart", "Walmart Canada", "Amazon.ca"], stores_us: ["Target", "Walmart"],
    available_ca: true, available_us: true, tags: ["lips", "lipstick"] }),
  p({ slug: "wet-n-wild-megalast-lipstick", name: "MegaLast Matte Lipstick", brand: "Wet n Wild", category: "Makeup",
    description: "Long-wearing matte lipstick at one of the lowest prices in the aisle.",
    price_cad: 5, price_usd: 3, certification: "PETA", vegan: true, emoji: "💄",
    stores_ca: ["Walmart Canada", "Amazon.ca"], stores_us: ["Walmart", "CVS", "Walgreens"],
    available_ca: true, available_us: true, tags: ["lips", "lipstick", "budget"] }),
  p({ slug: "milani-baked-blush", name: "Baked Blush", brand: "Milani", category: "Makeup",
    description: "Baked powder blush with a luminous finish. Cruelty-free drugstore staple.",
    price_cad: 12, price_usd: 9, certification: "PETA", vegan: false, emoji: "🌸",
    stores_ca: ["Walmart Canada", "Amazon.ca"], stores_us: ["Target", "Walmart", "CVS"],
    available_ca: true, available_us: true, tags: ["blush", "face"] }),
  p({ slug: "nyx-epic-ink-liner", name: "Epic Ink Liner", brand: "NYX Professional Makeup", category: "Makeup",
    description: "Waterproof felt-tip liquid eyeliner. Vegan.",
    price_cad: 12, price_usd: 9, certification: "PETA", vegan: true, emoji: "✒️",
    stores_ca: ["Shoppers Drug Mart", "Amazon.ca"], stores_us: ["Target", "Ulta", "CVS"],
    available_ca: true, available_us: true, tags: ["eyeliner", "eyes"] }),
  p({ slug: "elf-halo-glow-filter", name: "Halo Glow Liquid Filter", brand: "e.l.f.", category: "Makeup",
    description: "Glow booster/complexion enhancer — a budget alternative to prestige glow drops.",
    price_cad: 18, price_usd: 14, certification: "PETA", vegan: true, emoji: "✨",
    stores_ca: ["Shoppers Drug Mart", "Amazon.ca"], stores_us: ["Target", "Ulta"],
    available_ca: true, available_us: true, tags: ["face", "highlighter", "bestseller"] }),
  p({ slug: "pacifica-alight-bb-cream", name: "Alight Multi-Mineral BB Cream", brand: "Pacifica", category: "Makeup",
    description: "Sheer-coverage vegan BB cream from a 100% vegan, cruelty-free brand.",
    price_cad: 20, price_usd: 16, certification: "Leaping Bunny + PETA", vegan: true, emoji: "🧴",
    stores_ca: ["Well.ca", "Amazon.ca", "London Drugs"], stores_us: ["Target", "Whole Foods", "Amazon.com"],
    available_ca: true, available_us: true, tags: ["bb cream", "face"] }),

  // ---------- SKINCARE ----------
  p({ slug: "ordinary-natural-moisturizing-factors", name: "Natural Moisturizing Factors + HA", brand: "The Ordinary", category: "Skincare",
    description: "No-frills daily moisturizer from Canadian-founded, cruelty-free The Ordinary.",
    price_cad: 12, price_usd: 10, certification: "PETA", vegan: true, emoji: "🧴",
    stores_ca: ["Shoppers Drug Mart", "Sephora Canada", "Well.ca"], stores_us: ["Target", "Sephora", "Ulta"],
    available_ca: true, available_us: true, tags: ["moisturizer", "face", "budget", "canadian"] }),
  p({ slug: "ordinary-squalane-cleanser", name: "Squalane Cleanser", brand: "The Ordinary", category: "Skincare",
    description: "Gentle balm-to-oil cleanser that removes makeup without stripping.",
    price_cad: 11, price_usd: 9, certification: "PETA", vegan: true, emoji: "🧼",
    stores_ca: ["Shoppers Drug Mart", "Sephora Canada", "Well.ca"], stores_us: ["Target", "Sephora", "Ulta"],
    available_ca: true, available_us: true, tags: ["cleanser", "face", "canadian"] }),
  p({ slug: "ordinary-niacinamide", name: "Niacinamide 10% + Zinc 1%", brand: "The Ordinary", category: "Skincare",
    description: "Best-selling blemish and pore serum — a fraction of the price of prestige serums.",
    price_cad: 9, price_usd: 7, certification: "PETA", vegan: true, emoji: "💧",
    stores_ca: ["Shoppers Drug Mart", "Sephora Canada", "Well.ca"], stores_us: ["Target", "Sephora", "Ulta"],
    available_ca: true, available_us: true, tags: ["serum", "face", "budget", "bestseller", "canadian"] }),
  p({ slug: "pacifica-sea-c-serum", name: "Glow Baby Vitamin C Serum", brand: "Pacifica", category: "Skincare",
    description: "Brightening vitamin C serum, 100% vegan.",
    price_cad: 22, price_usd: 18, certification: "Leaping Bunny + PETA", vegan: true, emoji: "🍊",
    stores_ca: ["Well.ca", "Amazon.ca"], stores_us: ["Target", "Ulta", "Whole Foods"],
    available_ca: true, available_us: true, tags: ["serum", "vitamin c", "face"] }),
  p({ slug: "green-beaver-spf30", name: "Adult Natural Mineral Sunscreen SPF 30", brand: "Green Beaver", category: "Skincare",
    description: "Canadian-made mineral sunscreen, Leaping Bunny certified.",
    price_cad: 25, price_usd: 19, certification: "Leaping Bunny", vegan: true, emoji: "☀️",
    stores_ca: ["Well.ca", "London Drugs", "Amazon.ca"], stores_us: ["Amazon.com"],
    available_ca: true, available_us: true, tags: ["sunscreen", "spf", "canadian"] }),
  p({ slug: "derma-e-vitamin-e-cream", name: "Vitamin E 12,000 IU Intensive Cream", brand: "DERMA E", category: "Skincare",
    description: "Rich all-purpose moisture cream for face and body.",
    price_cad: 18, price_usd: 14, certification: "Leaping Bunny + PETA", vegan: true, emoji: "🧴",
    stores_ca: ["Well.ca", "Amazon.ca"], stores_us: ["Target", "Whole Foods", "Walgreens"],
    available_ca: true, available_us: true, tags: ["moisturizer", "body", "face"] }),
  p({ slug: "acure-brightening-scrub", name: "Brightening Facial Scrub", brand: "Acure", category: "Skincare",
    description: "Sea-kelp facial scrub from a 100% vegan brand.",
    price_cad: 15, price_usd: 11, certification: "Leaping Bunny", vegan: true, emoji: "🌊",
    stores_ca: ["Well.ca", "Amazon.ca"], stores_us: ["Target", "Whole Foods", "Walgreens"],
    available_ca: true, available_us: true, tags: ["scrub", "exfoliant", "face"] }),

  // ---------- HAIR ----------
  p({ slug: "live-clean-argan-shampoo", name: "Exotic Nectar Argan Oil Shampoo", brand: "Live Clean", category: "Hair",
    description: "Canadian brand, plant-derived, widely available and inexpensive.",
    price_cad: 8, price_usd: 7, certification: "Leaping Bunny", vegan: true, emoji: "🧴",
    stores_ca: ["Walmart Canada", "Shoppers Drug Mart", "Well.ca"], stores_us: ["Amazon.com"],
    available_ca: true, available_us: true, tags: ["shampoo", "budget", "canadian"] }),
  p({ slug: "attitude-super-leaves-shampoo", name: "Super Leaves Nourishing Shampoo", brand: "ATTITUDE", category: "Hair",
    description: "Montreal-based, EWG-verified, refill-friendly shampoo.",
    price_cad: 12, price_usd: 10, certification: "PETA", vegan: true, emoji: "🍃",
    stores_ca: ["Well.ca", "Amazon.ca", "London Drugs"], stores_us: ["Amazon.com", "Whole Foods"],
    available_ca: true, available_us: true, tags: ["shampoo", "canadian", "eco"] }),
  p({ slug: "pacifica-glow-baby-conditioner", name: "Glow Baby Brightening Conditioner", brand: "Pacifica", category: "Hair",
    description: "Vegan conditioner for shine and softness.",
    price_cad: 13, price_usd: 10, certification: "Leaping Bunny + PETA", vegan: true, emoji: "🧴",
    stores_ca: ["Well.ca", "Amazon.ca"], stores_us: ["Target", "Ulta"],
    available_ca: true, available_us: true, tags: ["conditioner"] }),
  p({ slug: "not-your-mothers-dry-shampoo", name: "Clean Freak Dry Shampoo", brand: "Not Your Mother's", category: "Hair",
    description: "Budget dry shampoo, PETA certified.",
    price_cad: 10, price_usd: 7, certification: "PETA", vegan: false, emoji: "💨",
    stores_ca: ["Walmart Canada", "Amazon.ca"], stores_us: ["Target", "Walmart", "CVS"],
    available_ca: true, available_us: true, tags: ["dry shampoo", "budget"] }),
  p({ slug: "shea-moisture-coconut-hibiscus", name: "Coconut & Hibiscus Curl & Shine Shampoo", brand: "SheaMoisture", category: "Hair",
    description: "Curl-defining sulfate-free shampoo, cruelty-free and fair trade.",
    price_cad: 15, price_usd: 11, certification: "PETA", vegan: false, emoji: "🥥",
    stores_ca: ["Walmart Canada", "Shoppers Drug Mart", "Amazon.ca"], stores_us: ["Target", "Walmart", "CVS"],
    available_ca: true, available_us: true, tags: ["shampoo", "curly hair"] }),

  // ---------- BODY ----------
  p({ slug: "schmidts-charcoal-deodorant", name: "Charcoal + Magnesium Natural Deodorant", brand: "Schmidt's", category: "Body",
    description: "Aluminum-free natural deodorant, certified vegan and cruelty-free.",
    price_cad: 8, price_usd: 6, certification: "PETA", vegan: true, emoji: "🌿",
    stores_ca: ["Shoppers Drug Mart", "Walmart Canada", "Well.ca"], stores_us: ["Target", "Walmart", "CVS"],
    available_ca: true, available_us: true, tags: ["deodorant", "aluminum-free"] }),
  p({ slug: "native-coconut-vanilla-deodorant", name: "Coconut & Vanilla Deodorant", brand: "Native", category: "Body",
    description: "Popular aluminum-free deodorant, cruelty-free.",
    price_cad: 17, price_usd: 13, certification: "PETA", vegan: false, emoji: "🥥",
    stores_ca: ["Amazon.ca"], stores_us: ["Target", "Walmart", "CVS", "Walgreens"],
    available_ca: true, available_us: true, tags: ["deodorant", "aluminum-free"] }),
  p({ slug: "dr-bronners-castile-soap", name: "Pure-Castile Liquid Soap (Peppermint)", brand: "Dr. Bronner's", category: "Body",
    description: "18-in-1 concentrated castile soap — body wash, hand soap and more. Extremely economical per use.",
    price_cad: 16, price_usd: 13, certification: "Leaping Bunny", vegan: true, emoji: "🧼",
    stores_ca: ["Well.ca", "London Drugs", "Amazon.ca"], stores_us: ["Target", "Whole Foods", "Walmart"],
    available_ca: true, available_us: true, tags: ["body wash", "soap", "multi-purpose", "bestseller"] }),
  p({ slug: "method-body-wash", name: "Daily Zen Body Wash", brand: "Method", category: "Body",
    description: "Plant-based body wash in recycled packaging, Leaping Bunny certified.",
    price_cad: 9, price_usd: 7, certification: "Leaping Bunny", vegan: true, emoji: "🚿",
    stores_ca: ["Walmart Canada", "Well.ca"], stores_us: ["Target", "Walmart"],
    available_ca: true, available_us: true, tags: ["body wash", "budget"] }),
  p({ slug: "attitude-body-lotion", name: "Sensitive Skin Body Lotion", brand: "ATTITUDE", category: "Body",
    description: "Fragrance-free oatmeal lotion for sensitive skin, made in Canada.",
    price_cad: 13, price_usd: 11, certification: "PETA", vegan: true, emoji: "🧴",
    stores_ca: ["Well.ca", "Amazon.ca", "London Drugs"], stores_us: ["Amazon.com"],
    available_ca: true, available_us: true, tags: ["lotion", "sensitive skin", "canadian"] }),
  p({ slug: "method-gel-hand-wash", name: "Gel Hand Wash (Sweet Water)", brand: "Method", category: "Body",
    description: "Everyday hand soap, refill pouches available to cut cost and plastic.",
    price_cad: 5, price_usd: 4, certification: "Leaping Bunny", vegan: true, emoji: "🖐️",
    stores_ca: ["Walmart Canada", "Well.ca"], stores_us: ["Target", "Walmart", "Kroger"],
    available_ca: true, available_us: true, tags: ["hand soap", "budget"] }),
  p({ slug: "preserve-triple-razor", name: "Triple Razor (Recycled Handle)", brand: "Preserve", category: "Body",
    description: "Razor with handle made from recycled yogurt cups. Cruelty-free replacement for major razor brands.",
    price_cad: 12, price_usd: 9, certification: "Leaping Bunny", vegan: true, emoji: "🪒",
    stores_ca: ["Well.ca", "Amazon.ca"], stores_us: ["Whole Foods", "Amazon.com"],
    available_ca: true, available_us: true, tags: ["razor", "shaving", "eco"] }),
  p({ slug: "kiss-my-face-shave-cream", name: "Moisture Shave Cream", brand: "Kiss My Face", category: "Body",
    description: "Long-running cruelty-free shave cream, very economical per shave.",
    price_cad: 11, price_usd: 8, certification: "Leaping Bunny", vegan: true, emoji: "🫧",
    stores_ca: ["Well.ca", "Amazon.ca"], stores_us: ["Whole Foods", "Amazon.com"],
    available_ca: true, available_us: true, tags: ["shaving"] }),

  // ---------- ORAL CARE ----------
  p({ slug: "toms-whole-care-toothpaste", name: "Whole Care Natural Toothpaste", brand: "Tom's of Maine", category: "Oral Care",
    description: "Fluoride toothpaste from a Leaping Bunny certified brand.",
    price_cad: 6, price_usd: 5, certification: "Leaping Bunny", vegan: false, emoji: "🦷",
    stores_ca: ["Walmart Canada", "Well.ca", "Shoppers Drug Mart"], stores_us: ["Target", "Walmart", "CVS"],
    available_ca: true, available_us: true, tags: ["toothpaste", "fluoride"] }),
  p({ slug: "hello-antiplaque-toothpaste", name: "Antiplaque + Whitening Toothpaste", brand: "hello", category: "Oral Care",
    description: "Fluoride-free whitening toothpaste, PETA certified, vegan.",
    price_cad: 7, price_usd: 5, certification: "PETA", vegan: true, emoji: "🦷",
    stores_ca: ["Walmart Canada", "Amazon.ca"], stores_us: ["Target", "Walmart", "CVS", "Walgreens"],
    available_ca: true, available_us: true, tags: ["toothpaste", "whitening"] }),
  p({ slug: "hello-fresh-mint-mouthwash", name: "Fresh Mint Moisturizing Mouthwash", brand: "hello", category: "Oral Care",
    description: "Alcohol-free mouthwash, vegan and cruelty-free.",
    price_cad: 8, price_usd: 6, certification: "PETA", vegan: true, emoji: "🌬️",
    stores_ca: ["Walmart Canada", "Amazon.ca"], stores_us: ["Target", "Walmart", "CVS"],
    available_ca: true, available_us: true, tags: ["mouthwash"] }),
  p({ slug: "radius-source-toothbrush", name: "Source Floss Toothbrush", brand: "RADIUS", category: "Oral Care",
    description: "Replaceable-head toothbrush — cheaper over time and less waste.",
    price_cad: 10, price_usd: 8, certification: "Leaping Bunny", vegan: true, emoji: "🪥",
    stores_ca: ["Well.ca", "Amazon.ca"], stores_us: ["Whole Foods", "Amazon.com"],
    available_ca: true, available_us: true, tags: ["toothbrush", "eco"] }),

  // ---------- HOUSEHOLD ----------
  p({ slug: "nature-clean-laundry", name: "Laundry Liquid (Unscented)", brand: "Nature Clean", category: "Household",
    description: "Toronto-made, hypoallergenic laundry detergent. Certified cruelty-free.",
    price_cad: 13, price_usd: 11, certification: "Leaping Bunny", vegan: true, emoji: "🧺",
    stores_ca: ["Well.ca", "London Drugs", "Loblaws"], stores_us: ["Amazon.com"],
    available_ca: true, available_us: true, tags: ["laundry", "unscented", "canadian"] }),
  p({ slug: "ecos-laundry-detergent", name: "ECOS Laundry Detergent (Magnolia & Lily)", brand: "ECOS", category: "Household",
    description: "Plant-powered detergent with built-in fabric softener, ~100 loads per jug.",
    price_cad: 17, price_usd: 13, certification: "Leaping Bunny", vegan: true, emoji: "🧺",
    stores_ca: ["Well.ca", "Amazon.ca"], stores_us: ["Target", "Walmart", "Kroger"],
    available_ca: true, available_us: true, tags: ["laundry", "value"] }),
  p({ slug: "seventh-gen-dish-liquid", name: "Dish Liquid (Free & Clear)", brand: "Seventh Generation", category: "Household",
    description: "Fragrance-free plant-based dish soap, Leaping Bunny certified.",
    price_cad: 5, price_usd: 4, certification: "Leaping Bunny", vegan: true, emoji: "🍽️",
    stores_ca: ["Walmart Canada", "Loblaws", "Well.ca"], stores_us: ["Target", "Walmart", "Kroger"],
    available_ca: true, available_us: true, tags: ["dish soap", "budget", "unscented"] }),
  p({ slug: "attitude-all-purpose-cleaner", name: "All-Purpose Cleaner (Citrus Zest)", brand: "ATTITUDE", category: "Household",
    description: "Canadian-made all-purpose spray, EWG verified.",
    price_cad: 6, price_usd: 5, certification: "PETA", vegan: true, emoji: "🧽",
    stores_ca: ["Well.ca", "London Drugs", "Amazon.ca"], stores_us: ["Amazon.com", "Whole Foods"],
    available_ca: true, available_us: true, tags: ["cleaner", "canadian", "budget"] }),
  p({ slug: "method-all-purpose-cleaner", name: "All-Purpose Cleaner (French Lavender)", brand: "Method", category: "Household",
    description: "Plant-based surface cleaner, widely available.",
    price_cad: 6, price_usd: 4, certification: "Leaping Bunny", vegan: true, emoji: "💜",
    stores_ca: ["Walmart Canada", "Canadian Tire"], stores_us: ["Target", "Walmart", "Kroger"],
    available_ca: true, available_us: true, tags: ["cleaner", "budget"] }),
  p({ slug: "ecover-dishwasher-tablets", name: "Dishwasher Tablets (Citrus)", brand: "Ecover", category: "Household",
    description: "Phosphate-free dishwasher tabs, Leaping Bunny certified.",
    price_cad: 12, price_usd: 9, certification: "Leaping Bunny", vegan: true, emoji: "🫧",
    stores_ca: ["Well.ca", "Amazon.ca"], stores_us: ["Whole Foods", "Amazon.com"],
    available_ca: true, available_us: true, tags: ["dishwasher"] }),
  p({ slug: "biokleen-bac-out", name: "Bac-Out Stain & Odor Remover", brand: "Biokleen", category: "Household",
    description: "Enzyme stain remover for laundry, carpets and pet messes.",
    price_cad: 14, price_usd: 10, certification: "Leaping Bunny", vegan: true, emoji: "🐾",
    stores_ca: ["Well.ca", "Amazon.ca"], stores_us: ["Whole Foods", "Amazon.com", "Kroger"],
    available_ca: true, available_us: true, tags: ["stain remover", "pets"] }),
];

// Conventional item -> cruelty-free lower/similar-cost alternative
type S = Omit<Swap, "id">;
const s = (x: S, i: number): Swap => ({ ...x, id: `swap-${i + 1}` });

export const seedSwaps: Swap[] = ([
  { conventional_name: "Great Lash / Lash Sensational Mascara", conventional_brand: "Maybelline", conventional_price_cad: 11, conventional_price_usd: 9,
    product_slug: "essence-lash-princess", note: "Essence Lash Princess is the classic budget swap — usually cheaper and top-rated." },
  { conventional_name: "Voluminous Mascara", conventional_brand: "L'Oréal", conventional_price_cad: 14, conventional_price_usd: 11,
    product_slug: "covergirl-lashblast-volume", note: "CoverGirl is Leaping Bunny certified across its whole line." },
  { conventional_name: "Fit Me Foundation", conventional_brand: "Maybelline", conventional_price_cad: 13, conventional_price_usd: 10,
    product_slug: "elf-flawless-satin-foundation", note: "Similar coverage and shade range for less." },
  { conventional_name: "True Match Foundation", conventional_brand: "L'Oréal", conventional_price_cad: 18, conventional_price_usd: 14,
    product_slug: "covergirl-clean-fresh-foundation", note: "Lighter feel, certified cruelty-free." },
  { conventional_name: "Superstay Matte Ink Lipstick", conventional_brand: "Maybelline", conventional_price_cad: 15, conventional_price_usd: 12,
    product_slug: "wet-n-wild-megalast-lipstick", note: "A third of the price and vegan." },
  { conventional_name: "Head & Shoulders Shampoo", conventional_brand: "P&G", conventional_price_cad: 9, conventional_price_usd: 7,
    product_slug: "live-clean-argan-shampoo", note: "Canadian-made and about the same price." },
  { conventional_name: "Pantene Pro-V Shampoo", conventional_brand: "P&G", conventional_price_cad: 8, conventional_price_usd: 6,
    product_slug: "attitude-super-leaves-shampoo", note: "Slightly more, but EWG-verified with refills that lower long-run cost." },
  { conventional_name: "Batiste Dry Shampoo", conventional_brand: "Batiste", conventional_price_cad: 11, conventional_price_usd: 9,
    product_slug: "not-your-mothers-dry-shampoo", note: "Cheaper and PETA certified." },
  { conventional_name: "Secret / Old Spice Deodorant", conventional_brand: "P&G", conventional_price_cad: 8, conventional_price_usd: 6,
    product_slug: "schmidts-charcoal-deodorant", note: "Aluminum-free at a comparable price." },
  { conventional_name: "Dove Body Wash", conventional_brand: "Unilever", conventional_price_cad: 8, conventional_price_usd: 6,
    product_slug: "method-body-wash", note: "Comparable price, Leaping Bunny certified." },
  { conventional_name: "Softsoap Hand Soap", conventional_brand: "Colgate-Palmolive", conventional_price_cad: 4, conventional_price_usd: 3,
    product_slug: "method-gel-hand-wash", note: "Nearly identical price; refill pouches make it cheaper over time." },
  { conventional_name: "Gillette Venus / Mach3 Razor", conventional_brand: "Gillette", conventional_price_cad: 15, conventional_price_usd: 12,
    product_slug: "preserve-triple-razor", note: "Cheaper handle, recycled materials, cruelty-free blades." },
  { conventional_name: "Colgate Total Toothpaste", conventional_brand: "Colgate", conventional_price_cad: 5, conventional_price_usd: 4,
    product_slug: "toms-whole-care-toothpaste", note: "Fluoride option from a Leaping Bunny brand at a similar price." },
  { conventional_name: "Crest 3D White Toothpaste", conventional_brand: "P&G", conventional_price_cad: 6, conventional_price_usd: 5,
    product_slug: "hello-antiplaque-toothpaste", note: "Whitening swap, vegan." },
  { conventional_name: "Listerine Mouthwash", conventional_brand: "Kenvue", conventional_price_cad: 9, conventional_price_usd: 7,
    product_slug: "hello-fresh-mint-mouthwash", note: "Alcohol-free and about the same price." },
  { conventional_name: "Tide Laundry Detergent", conventional_brand: "P&G", conventional_price_cad: 20, conventional_price_usd: 15,
    product_slug: "ecos-laundry-detergent", note: "Lower cost per load (~100 loads) and Leaping Bunny certified." },
  { conventional_name: "Dawn Dish Soap", conventional_brand: "P&G", conventional_price_cad: 5, conventional_price_usd: 4,
    product_slug: "seventh-gen-dish-liquid", note: "Same shelf price, plant-based." },
  { conventional_name: "Mr. Clean All-Purpose Cleaner", conventional_brand: "P&G", conventional_price_cad: 7, conventional_price_usd: 5,
    product_slug: "method-all-purpose-cleaner", note: "Cheaper and plant-based." },
  { conventional_name: "Cascade Dishwasher Pods", conventional_brand: "P&G", conventional_price_cad: 15, conventional_price_usd: 12,
    product_slug: "ecover-dishwasher-tablets", note: "Comparable per-wash cost, phosphate-free." },
  { conventional_name: "OxiClean Stain Remover", conventional_brand: "Church & Dwight", conventional_price_cad: 13, conventional_price_usd: 10,
    product_slug: "biokleen-bac-out", note: "Enzyme-based swap at a similar price." },
  { conventional_name: "CeraVe Moisturizing Cream", conventional_brand: "L'Oréal", conventional_price_cad: 20, conventional_price_usd: 17,
    product_slug: "ordinary-natural-moisturizing-factors", note: "Much cheaper daily moisturizer from a cruelty-free brand." },
  { conventional_name: "Neutrogena Sunscreen SPF 30", conventional_brand: "Kenvue", conventional_price_cad: 16, conventional_price_usd: 12,
    product_slug: "green-beaver-spf30", note: "Mineral, made in Canada. Costs a bit more — the cruelty-free premium here." },
  { conventional_name: "Olay Regenerist Serum", conventional_brand: "P&G", conventional_price_cad: 35, conventional_price_usd: 29,
    product_slug: "ordinary-niacinamide", note: "A quarter of the price for a top-rated serum." },
  { conventional_name: "Barbasol / Skintimate Shave Cream", conventional_brand: "Perio / Edgewell", conventional_price_cad: 5, conventional_price_usd: 3,
    product_slug: "kiss-my-face-shave-cream", note: "More upfront but concentrated — comparable per shave." },
] as S[]).map(s);
