// Generates supabase/seed.sql from lib/seed-data.ts (single source of truth).
// Run: npm run gen:seed
import { readFileSync, writeFileSync } from "node:fs";
import { execSync } from "node:child_process";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.dirname(path.dirname(fileURLToPath(import.meta.url)));

// Transpile the TS seed file to a temp mjs via a quick strip of types using esbuild if present,
// otherwise use a naive dynamic import through tsx-free approach: precompiled JSON fallback.
let seedProducts, seedSwaps;
try {
  execSync(
    `npx --yes esbuild lib/seed-data.ts lib/types.ts --outdir=.seedtmp --format=esm --platform=node --out-extension:.js=.mjs`,
    { cwd: root, stdio: "inherit" }
  );
  ({ seedProducts, seedSwaps } = await import(path.join(root, ".seedtmp/seed-data.mjs")));
} catch (e) {
  console.error("esbuild transpile failed:", e.message);
  process.exit(1);
}

const q = (s) => `'${String(s).replace(/'/g, "''")}'`;
const arr = (a) => `ARRAY[${a.map(q).join(", ")}]::text[]`;

let sql = `-- Generated by scripts/generate-seed.mjs — do not edit by hand.\n-- Run schema.sql first.\n\n`;

for (const p of seedProducts) {
  sql += `insert into products (id, slug, name, brand, category, description, price_cad, price_usd, certification, vegan, emoji, stores_ca, stores_us, available_ca, available_us, tags) values (${q(p.id)}, ${q(p.slug)}, ${q(p.name)}, ${q(p.brand)}, ${q(p.category)}, ${q(p.description)}, ${p.price_cad}, ${p.price_usd}, ${q(p.certification)}, ${p.vegan}, ${q(p.emoji)}, ${arr(p.stores_ca)}, ${arr(p.stores_us)}, ${p.available_ca}, ${p.available_us}, ${arr(p.tags)}) on conflict (id) do nothing;\n`;
}
sql += `\n`;
for (const s of seedSwaps) {
  sql += `insert into swaps (id, conventional_name, conventional_brand, conventional_price_cad, conventional_price_usd, product_slug, note) values (${q(s.id)}, ${q(s.conventional_name)}, ${q(s.conventional_brand)}, ${s.conventional_price_cad}, ${s.conventional_price_usd}, ${q(s.product_slug)}, ${q(s.note)}) on conflict (id) do nothing;\n`;
}

writeFileSync(path.join(root, "supabase/seed.sql"), sql);
console.log(`Wrote supabase/seed.sql (${seedProducts.length} products, ${seedSwaps.length} swaps)`);
